/*
  # Paiements Fournisseur — table dettes_fournisseur

  ## Description
  Suivi des paiements USD effectués par CEC en Chine pour le compte de ses clients.
  Le client nous rembourse en MGA depuis la caisse. Chaque dette reçoit une référence
  unique (DF-YYYY-NNN) qui peut être citée lors des remboursements en caisse.

  ## Nouvelles tables
  - `dettes_fournisseur`
    - `id` — clé primaire
    - `reference` — référence unique format DF-YYYY-NNN
    - `client_id` — client pour qui le paiement a été effectué
    - `montant_usd` — montant payé en USD en Chine
    - `taux_usd_mga` — taux USD/MGA utilisé
    - `montant_mga_equivalent` — équivalent MGA de la dette (calculé)
    - `description` — objet du paiement
    - `date_paiement` — date du paiement USD
    - `statut` — en_attente | partiellement_remboursee | remboursee
    - `montant_rembourse_mga` — cumul des remboursements caisse reçus
    - `notes` — notes internes optionnelles
    - `saisie_par_id` — agent qui a saisi la dette
    - `est_annule`, `annule_par_id`, `annule_at`, `motif_annulation` — annulation avec audit

  ## Modifications tables existantes
  - `mouvements_caisse` : ajout colonne `dette_fournisseur_id` (FK vers dettes_fournisseur)

  ## Sécurité
  - RLS activé sur `dettes_fournisseur`
  - Lecture : tous les agents authentifiés
  - Insertion : agents authentifiés
  - Mise à jour : admin et trésorier seulement
  - Suppression : interdite (utiliser annulation)
*/

-- Table principale
CREATE TABLE IF NOT EXISTS dettes_fournisseur (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference text NOT NULL UNIQUE,
  client_id bigint NOT NULL REFERENCES clients(id),
  montant_usd numeric(14, 4) NOT NULL CHECK (montant_usd > 0),
  taux_usd_mga numeric(14, 2) NOT NULL CHECK (taux_usd_mga > 0),
  montant_mga_equivalent numeric(14, 2) NOT NULL,
  description text NOT NULL DEFAULT '',
  date_paiement date NOT NULL,
  statut text NOT NULL DEFAULT 'en_attente' CHECK (statut IN ('en_attente', 'partiellement_remboursee', 'remboursee')),
  montant_rembourse_mga numeric(14, 2) NOT NULL DEFAULT 0,
  notes text,
  saisie_par_id uuid NOT NULL REFERENCES employees(user_id),
  est_annule boolean NOT NULL DEFAULT false,
  annule_par_id uuid REFERENCES employees(user_id),
  annule_at timestamptz,
  motif_annulation text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Index performance
CREATE INDEX IF NOT EXISTS idx_dettes_fournisseur_client ON dettes_fournisseur(client_id);
CREATE INDEX IF NOT EXISTS idx_dettes_fournisseur_statut ON dettes_fournisseur(statut);
CREATE INDEX IF NOT EXISTS idx_dettes_fournisseur_date ON dettes_fournisseur(date_paiement DESC);

-- Trigger updated_at
CREATE OR REPLACE FUNCTION update_dettes_fournisseur_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_dettes_fournisseur_updated_at
  BEFORE UPDATE ON dettes_fournisseur
  FOR EACH ROW EXECUTE FUNCTION update_dettes_fournisseur_updated_at();

-- RLS
ALTER TABLE dettes_fournisseur ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Agents authenticated can read dettes fournisseur"
  ON dettes_fournisseur FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Agents authenticated can insert dettes fournisseur"
  ON dettes_fournisseur FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = saisie_par_id);

CREATE POLICY "Admin and tresorier can update dettes fournisseur"
  ON dettes_fournisseur FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM employees
      WHERE employees.user_id = auth.uid()
        AND employees.role IN ('administrateur', 'tresorier')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM employees
      WHERE employees.user_id = auth.uid()
        AND employees.role IN ('administrateur', 'tresorier')
    )
  );

-- Colonne FK sur mouvements_caisse
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'mouvements_caisse' AND column_name = 'dette_fournisseur_id'
  ) THEN
    ALTER TABLE mouvements_caisse ADD COLUMN dette_fournisseur_id bigint REFERENCES dettes_fournisseur(id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_mouvements_caisse_dette_fournisseur ON mouvements_caisse(dette_fournisseur_id);
